add holidays to core standing time
rl-institut/spice_ev pull request #103
Opened 2022-06-03 08:45 UTC by stefansc1

2022-06-13 13:49 UTC, jakobgemassmer requested changes
Code in util.py works. Holidays are also written into scenario.json, but not treated equally to full_days in the flex_band. The flex_band ignores the "holidays". Holidays are also not consired, when generating synthetic driving profiles.

- [x] Treat holidays equally to full_days in `generate_schedule.py`.
- [ ] Add holidays to `generate.py` (via generate.cfg as in generate_schedule.cfg), so they are consired when creating syntetic driving profiles (like `no_drive_days`).

2022-06-15 09:28 UTC, stefansc1 commented
- added holidays to generate and generate.cfg (config-option only)
- using datetime.weekday instead of isoweekday (off-by-one). Sunday is now 6 instead of 7
- renamed full_days to no_drive_days
- updated tests
- updated RTD

2022-06-15 14:24 UTC, jakobgemassmer requested changes
Just a minor name change in the docstrings of generate_schedule.py. Everything else seems solid.

2022-06-15 14:24 UTC, jakobgemassmer commented on generate_schedule.py
> +        {"times":[{"start": [22,0], "end":[5,0]}], "full_days":[6]}
```suggestion
        {"times":[{"start": [22,0], "end":[5,0]}], "no_drive_days":[6]}
```

2022-06-15 14:29 UTC, merged