Feature/feedin split
rl-institut/spice_ev pull request #161
Opened 2023-03-15 15:05 UTC by j-ti

Fixes #135

**Changes proposed in this pull request**:
- Your changes

The following steps were realized (required):
- [ ] Correct linting with `flake8 path_to_script`
- [ ] Check if tests pass locally with `python -m pytest tests/`

Also the following steps were realized (if applies):
- [ ] Write docstrings to your code
- [ ] Explain new functionalities in readthedocs
- [ ] Write test(s) for new patch of code
- [ ] Check building of documentation with `doc/make html`

2023-03-15 16:20 UTC, j-ti commented
Preliminary results as below:
![spice_ev-feedin_split](https://user-images.githubusercontent.com/56872869/225373663-3b3af96b-53e6-47fb-90b4-073fb63604a1.png)
Todos:
- [x] feetin values should be negative

2023-03-28 10:49 UTC, jakobgemassmer commented on spice_ev/report.py
> +    print(hasFeedinComponents)
```suggestion

```

2023-03-28 10:58 UTC, jakobgemassmer commented on spice_ev/report.py
> +        - round(generated_feedin, round_to_places),
```suggestion
        round(generated_feedin, round_to_places),
```

2023-03-28 12:01 UTC, stefansc1 requested changes

2023-03-28 12:01 UTC, stefansc1 commented on spice_ev/report.py
> +    print(hasFeedinComponents)
remove print

2023-03-29 07:45 UTC, jakobgemassmer requested changes
add feed-in split by source to resulting json (also add in example files).

2023-03-29 07:45 UTC, jakobgemassmer commented on examples/output/simulation.csv
> +timestep,time,price [EUR/kWh],grid supply [kW],fixed load [kW],local generation [kW],flex band min [kW],flex band base [kW],flex band max [kW],generated feed-in [kW],V2G feed-in [kW],sum CS power [kW
```suggestion
timestep,time,price [EUR/kWh],grid supply [kW],fixed load [kW],local generation [kW],flex band min [kW],flex band base [kW],flex band max [kW],generation feed-in [kW],V2G feed-in [kW],sum CS power [kW],# occupied CS [-],# CS in use [-],C1 [kW],C2 [kW],C3 [kW]
```

2023-03-29 08:06 UTC, stefansc1 commented on spice_ev/report.py
> +    hasFeedinComponents = [any(scenario.localGenerationPower), True, bool(hasBatteries)]
suggested change:
```
hasV2G = any([v.vehicle_type.v2g for v in scenario.components.vehicles.values()])
hasBatteries = any([b.parent == gcID for b in scenario.components.batteries.values()])
hasFeedinComponents = [any(scenario.localGenerationPower), hasV2G, hasBatteries]
```

2023-03-31 11:43 UTC, j-ti commented on spice_ev/report.py
> +def split_feedin(grid, generation, cs_sum, round_to_places):
also added 3 as default parameter

2023-04-03 11:17 UTC, merged