Feature/feed in remuneration
rl-institut/spice_ev pull request #166
Opened 2023-04-18 07:11 UTC by TabeaMaria

Fixes #Issue

**Changes proposed in this pull request**:
- change calculation of feed-in remuneration for PV energy by using PV feed-in energy instead of total feed-in energy which includes V2G and Battery feed-in, too

The following steps were realized (required):
- [x] Correct linting with `flake8 path_to_script`
- [x] Check if tests pass locally with `python -m pytest tests/`

Also the following steps were realized (if applies):
- [x] Write docstrings to your code (adjust docstrings)
- [ ] Explain new functionalities in readthedocs
- [x] Write test(s) for new patch of code (ajdust tests)
- [ ] Check building of documentation with `doc/make html`

2023-04-18 07:24 UTC, stefansc1 reviewed
this WILL conflict with #165

2023-04-18 07:24 UTC, stefansc1 commented on calculate_costs.py
> +                power_generation_feed_in = 0.0
`power_generation_feed_in = float(row.get("generation feed-in [kW]", 0))`

2023-04-18 07:24 UTC, stefansc1 commented on spice_ev/costs.py
> +    # power_feed_in_list = [max(v, 0) for v in power_grid_supply_list]
comment can be removed?

2023-04-18 07:24 UTC, stefansc1 commented on tests/test_calculate_costs.py
add a test with actual feed-in cost calculation?

2023-04-18 08:20 UTC, TabeaMaria commented on spice_ev/costs.py
> +        * interval.total_seconds() / 3600  # [kWh]
Because this is only taking feed-in from local generation into account. Battery feed-in and V2G are not remunerated yet.

2023-04-18 08:25 UTC, TabeaMaria commented on tests/test_calculate_costs.py
In test_calculate_costs_advanced() scenario_PV_Bat is tested. Is this enough?

2023-04-18 09:09 UTC, stefansc1 commented on tests/test_calculate_costs.py
Yes, scenario_PV_Bat should be fine. scenario_B uses the example feed-in CSV, but does not define a PV component -- not sure if you can calculate costs for it.

2023-04-24 07:42 UTC, jakobgemassmer approved these changes

2023-04-24 07:42 UTC, jakobgemassmer commented on tests/test_data/input_test_strategies/scenario_B.json
> +      "PV_final_zeros": {
reverse this and merge dev to avoid merge conflicts

2023-04-24 07:42 UTC, jakobgemassmer commented on tests/test_data/input_test_strategies/scenario_PV_Bat.json
> +      "PV_feed-in": {
reverse this and merge dev to avoid merge conflicts

2023-04-24 07:56 UTC, stefansc1 requested changes

2023-04-24 07:56 UTC, stefansc1 commented on spice_ev/costs.py
> +    '''Calculates the feed-in remuneration per year and simulation period
use double quotation marks like every other docstring

2023-04-24 07:56 UTC, stefansc1 commented on spice_ev/costs.py
> +            energy_feed_in_per_year * feed_in_charge / 100)  # [EUR]
fits one line?

2023-04-24 07:56 UTC, stefansc1 commented on tests/test_calculate_costs.py
> +                [5] * 9,  # empty feed-in from local generation
if it's 5, it's not empty? Change comment

2023-04-24 07:56 UTC, stefansc1 commented on tests/test_calculate_costs.py
> +                   == result["power_procurement_costs_per_year"]
maybe work with brackets instead of backslashes: 
```
assert (results_json[...]
  == result[...])
```

2023-05-03 08:41 UTC, TabeaMaria commented on tests/test_calculate_costs.py
We later agreed on printing a warning if no nominal PV power but a PV feed-in list is given. Those changes have been made. So this conversation can be resolved, right?

2023-05-05 16:30 UTC, merged