Feature/generate from csv
rl-institut/spice_ev pull request #81
Opened 2022-02-22 12:42 UTC by Piranias

Fix #Issue

**Changes proposed in this pull request**:
- update generate_from_csv.py
- add option to assign vehicle_id if not given
- add options to assign consumption via soc, delta_soc or mileage and distance

The following steps were realized, as well (required):
- [x] Correct linting with `fake8 path_to_script`
- [x] Check if tests pass locally (`pytest ./src/tests.py`)

Also the following steps were realized (if applies):
- [x] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [x] Write test(s) for your new patch of code

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

2022-02-22 14:46 UTC, jakobgemassmer requested changes

2022-02-22 15:00 UTC, Piranias commented on generate_from_csv.py
> +            "min_power": 0.1 * cs_power,
I added a parameter to the argument parser / cfg file cs_power_min

2022-02-22 15:00 UTC, Piranias commented on generate_from_csv.py
> +    - soc or delta_soc (optional, if not given the milage is taken instead) in [0,1]
it's the soc at arrival. I added an explanation

2022-02-23 13:07 UTC, stefansc1 requested changes

2022-02-23 13:07 UTC, stefansc1 commented on generate_from_csv.py
> +    parser.add_argument('--cs-power-min', type=int, default=0, help='set minimal power at charging '
Might make that of type float

2022-02-23 13:07 UTC, stefansc1 commented on generate_from_csv.py
> +    parser.add_argument('--min-standing-time', type=int, default=None,
Might also be float instead of integer?

2022-02-24 10:06 UTC, merged